// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crowdfund/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetCrowdfundRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCrowdfundRequest) Reset()         { *m = QueryGetCrowdfundRequest{} }
func (m *QueryGetCrowdfundRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCrowdfundRequest) ProtoMessage()    {}
func (*QueryGetCrowdfundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{2}
}
func (m *QueryGetCrowdfundRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCrowdfundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCrowdfundRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCrowdfundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCrowdfundRequest.Merge(m, src)
}
func (m *QueryGetCrowdfundRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCrowdfundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCrowdfundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCrowdfundRequest proto.InternalMessageInfo

func (m *QueryGetCrowdfundRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCrowdfundResponse struct {
	Crowdfund Crowdfund `protobuf:"bytes,1,opt,name=Crowdfund,proto3" json:"Crowdfund"`
}

func (m *QueryGetCrowdfundResponse) Reset()         { *m = QueryGetCrowdfundResponse{} }
func (m *QueryGetCrowdfundResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCrowdfundResponse) ProtoMessage()    {}
func (*QueryGetCrowdfundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{3}
}
func (m *QueryGetCrowdfundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCrowdfundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCrowdfundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCrowdfundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCrowdfundResponse.Merge(m, src)
}
func (m *QueryGetCrowdfundResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCrowdfundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCrowdfundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCrowdfundResponse proto.InternalMessageInfo

func (m *QueryGetCrowdfundResponse) GetCrowdfund() Crowdfund {
	if m != nil {
		return m.Crowdfund
	}
	return Crowdfund{}
}

type QueryAllCrowdfundRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCrowdfundRequest) Reset()         { *m = QueryAllCrowdfundRequest{} }
func (m *QueryAllCrowdfundRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCrowdfundRequest) ProtoMessage()    {}
func (*QueryAllCrowdfundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{4}
}
func (m *QueryAllCrowdfundRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCrowdfundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCrowdfundRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCrowdfundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCrowdfundRequest.Merge(m, src)
}
func (m *QueryAllCrowdfundRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCrowdfundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCrowdfundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCrowdfundRequest proto.InternalMessageInfo

func (m *QueryAllCrowdfundRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCrowdfundResponse struct {
	Crowdfund  []Crowdfund         `protobuf:"bytes,1,rep,name=Crowdfund,proto3" json:"Crowdfund"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCrowdfundResponse) Reset()         { *m = QueryAllCrowdfundResponse{} }
func (m *QueryAllCrowdfundResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCrowdfundResponse) ProtoMessage()    {}
func (*QueryAllCrowdfundResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d40d9c8bf30e3a39, []int{5}
}
func (m *QueryAllCrowdfundResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCrowdfundResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCrowdfundResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCrowdfundResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCrowdfundResponse.Merge(m, src)
}
func (m *QueryAllCrowdfundResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCrowdfundResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCrowdfundResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCrowdfundResponse proto.InternalMessageInfo

func (m *QueryAllCrowdfundResponse) GetCrowdfund() []Crowdfund {
	if m != nil {
		return m.Crowdfund
	}
	return nil
}

func (m *QueryAllCrowdfundResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "cosmonaut.crowdfund.crowdfund.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "cosmonaut.crowdfund.crowdfund.QueryParamsResponse")
	proto.RegisterType((*QueryGetCrowdfundRequest)(nil), "cosmonaut.crowdfund.crowdfund.QueryGetCrowdfundRequest")
	proto.RegisterType((*QueryGetCrowdfundResponse)(nil), "cosmonaut.crowdfund.crowdfund.QueryGetCrowdfundResponse")
	proto.RegisterType((*QueryAllCrowdfundRequest)(nil), "cosmonaut.crowdfund.crowdfund.QueryAllCrowdfundRequest")
	proto.RegisterType((*QueryAllCrowdfundResponse)(nil), "cosmonaut.crowdfund.crowdfund.QueryAllCrowdfundResponse")
}

func init() { proto.RegisterFile("crowdfund/query.proto", fileDescriptor_d40d9c8bf30e3a39) }

var fileDescriptor_d40d9c8bf30e3a39 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6a, 0x14, 0x31,
	0x18, 0xc7, 0x37, 0xeb, 0xba, 0x60, 0x14, 0x0f, 0xb1, 0x4a, 0xbb, 0xe8, 0x28, 0x81, 0xda, 0x65,
	0xa1, 0x49, 0x77, 0x45, 0xf4, 0xda, 0x16, 0x2c, 0x88, 0x87, 0xba, 0xc7, 0xde, 0x32, 0x3b, 0x71,
	0x0c, 0xcc, 0x4e, 0xa6, 0x93, 0x8c, 0x5a, 0xc4, 0x8b, 0x4f, 0x20, 0x08, 0x1e, 0x7d, 0x08, 0xc5,
	0x77, 0xe8, 0xb1, 0xe0, 0xc5, 0x93, 0xc8, 0xae, 0x0f, 0x22, 0x9b, 0xa4, 0x33, 0xb3, 0x74, 0x70,
	0x66, 0xe9, 0xed, 0x23, 0xf3, 0xff, 0xff, 0xbf, 0xdf, 0x97, 0x7c, 0x0c, 0xbc, 0x3d, 0x49, 0xe5,
	0xdb, 0xe0, 0x55, 0x16, 0x07, 0xf4, 0x38, 0xe3, 0xe9, 0x09, 0x49, 0x52, 0xa9, 0x25, 0xba, 0x37,
	0x91, 0x6a, 0x2a, 0x63, 0x96, 0x69, 0x92, 0x0b, 0x8a, 0xaa, 0xb7, 0x16, 0xca, 0x50, 0x1a, 0x25,
	0x5d, 0x54, 0xd6, 0xd4, 0xbb, 0x1b, 0x4a, 0x19, 0x46, 0x9c, 0xb2, 0x44, 0x50, 0x16, 0xc7, 0x52,
	0x33, 0x2d, 0x64, 0xac, 0xdc, 0xd7, 0x81, 0x89, 0x54, 0xd4, 0x67, 0x8a, 0xdb, 0x5e, 0xf4, 0xcd,
	0xd0, 0xe7, 0x9a, 0x0d, 0x69, 0xc2, 0x42, 0x11, 0x1b, 0xb1, 0xd3, 0xde, 0x29, 0xa8, 0x12, 0x96,
	0xb2, 0xe9, 0x79, 0xc6, 0x46, 0x71, 0x5e, 0x60, 0x99, 0x4f, 0x78, 0x0d, 0xa2, 0x97, 0x8b, 0xd0,
	0x43, 0xa3, 0x1f, 0xf3, 0xe3, 0x8c, 0x2b, 0x8d, 0x8f, 0xe0, 0xad, 0xa5, 0x53, 0x95, 0xc8, 0x58,
	0x71, 0xb4, 0x0f, 0xbb, 0x36, 0x77, 0x1d, 0x3c, 0x00, 0xfd, 0xeb, 0xa3, 0x4d, 0xf2, 0xdf, 0x79,
	0x89, 0xb5, 0xef, 0x75, 0x4e, 0x7f, 0xdf, 0x6f, 0x8d, 0x9d, 0x15, 0x0f, 0xe0, 0xba, 0xc9, 0x3e,
	0xe0, 0x7a, 0xff, 0x5c, 0xe9, 0xfa, 0xa2, 0x9b, 0xb0, 0x2d, 0x02, 0x13, 0xde, 0x19, 0xb7, 0x45,
	0x80, 0x05, 0xdc, 0xa8, 0xd0, 0x3a, 0x9a, 0x17, 0xf0, 0x5a, 0x7e, 0xe8, 0x80, 0xfa, 0x35, 0x40,
	0xb9, 0xde, 0x31, 0x15, 0x01, 0xd8, 0x77, 0x58, 0xbb, 0x51, 0x74, 0x01, 0xeb, 0x19, 0x84, 0xc5,
	0x5d, 0xbb, 0x56, 0x0f, 0x6d, 0x2b, 0x45, 0x16, 0x0f, 0x43, 0xec, 0x12, 0xb8, 0x87, 0x21, 0x87,
	0x2c, 0xe4, 0xce, 0x3b, 0x2e, 0x39, 0xf1, 0x37, 0xe0, 0xe6, 0x59, 0x6e, 0x52, 0x3d, 0xcf, 0x95,
	0x4b, 0xcd, 0x83, 0x0e, 0x96, 0x98, 0xdb, 0x86, 0x79, 0xab, 0x96, 0xd9, 0xa2, 0x94, 0xa1, 0x47,
	0x5f, 0x3a, 0xf0, 0xaa, 0x81, 0x46, 0x5f, 0x01, 0xec, 0xda, 0x27, 0x45, 0xc3, 0x1a, 0xb0, 0x8b,
	0x3b, 0xd5, 0x1b, 0xad, 0x62, 0xb1, 0x1c, 0x78, 0xfb, 0xe3, 0xcf, 0xbf, 0x9f, 0xdb, 0x5b, 0x68,
	0x93, 0xe6, 0x5e, 0x5a, 0xb1, 0xcb, 0x6e, 0xdb, 0xd1, 0x0f, 0x50, 0xba, 0x42, 0xf4, 0xa4, 0x49,
	0xc3, 0x8a, 0x2d, 0xec, 0x3d, 0x5d, 0xdd, 0xe8, 0x78, 0x1f, 0x1b, 0x5e, 0x8a, 0xb6, 0x6b, 0x78,
	0x8b, 0xea, 0xbd, 0x08, 0x3e, 0xa0, 0xef, 0x00, 0xde, 0xc8, 0xc3, 0x76, 0xa3, 0xa8, 0x19, 0x7a,
	0xc5, 0xa6, 0x36, 0x43, 0xaf, 0xda, 0x3e, 0xbc, 0x63, 0xd0, 0x07, 0xa8, 0xdf, 0x14, 0x7d, 0xef,
	0xf9, 0xe9, 0xcc, 0x03, 0x67, 0x33, 0x0f, 0xfc, 0x99, 0x79, 0xe0, 0xd3, 0xdc, 0x6b, 0x9d, 0xcd,
	0xbd, 0xd6, 0xaf, 0xb9, 0xd7, 0x3a, 0xda, 0x09, 0x85, 0x7e, 0x9d, 0xf9, 0x64, 0x22, 0xa7, 0x95,
	0x69, 0xef, 0x4a, 0xb5, 0x3e, 0x49, 0xb8, 0xf2, 0xbb, 0xe6, 0x6f, 0xf4, 0xe8, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf2, 0x3b, 0xf8, 0x0c, 0x58, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Crowdfund by id.
	Crowdfund(ctx context.Context, in *QueryGetCrowdfundRequest, opts ...grpc.CallOption) (*QueryGetCrowdfundResponse, error)
	// Queries a list of Crowdfund items.
	CrowdfundAll(ctx context.Context, in *QueryAllCrowdfundRequest, opts ...grpc.CallOption) (*QueryAllCrowdfundResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Crowdfund(ctx context.Context, in *QueryGetCrowdfundRequest, opts ...grpc.CallOption) (*QueryGetCrowdfundResponse, error) {
	out := new(QueryGetCrowdfundResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Query/Crowdfund", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CrowdfundAll(ctx context.Context, in *QueryAllCrowdfundRequest, opts ...grpc.CallOption) (*QueryAllCrowdfundResponse, error) {
	out := new(QueryAllCrowdfundResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Query/CrowdfundAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Crowdfund by id.
	Crowdfund(context.Context, *QueryGetCrowdfundRequest) (*QueryGetCrowdfundResponse, error)
	// Queries a list of Crowdfund items.
	CrowdfundAll(context.Context, *QueryAllCrowdfundRequest) (*QueryAllCrowdfundResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Crowdfund(ctx context.Context, req *QueryGetCrowdfundRequest) (*QueryGetCrowdfundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Crowdfund not implemented")
}
func (*UnimplementedQueryServer) CrowdfundAll(ctx context.Context, req *QueryAllCrowdfundRequest) (*QueryAllCrowdfundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrowdfundAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Crowdfund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCrowdfundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Crowdfund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Query/Crowdfund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Crowdfund(ctx, req.(*QueryGetCrowdfundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CrowdfundAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCrowdfundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CrowdfundAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Query/CrowdfundAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CrowdfundAll(ctx, req.(*QueryAllCrowdfundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.crowdfund.crowdfund.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Crowdfund",
			Handler:    _Query_Crowdfund_Handler,
		},
		{
			MethodName: "CrowdfundAll",
			Handler:    _Query_CrowdfundAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crowdfund/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetCrowdfundRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCrowdfundRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCrowdfundRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCrowdfundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCrowdfundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCrowdfundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Crowdfund.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllCrowdfundRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCrowdfundRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCrowdfundRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCrowdfundResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCrowdfundResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCrowdfundResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Crowdfund) > 0 {
		for iNdEx := len(m.Crowdfund) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Crowdfund[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetCrowdfundRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCrowdfundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Crowdfund.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllCrowdfundRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCrowdfundResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Crowdfund) > 0 {
		for _, e := range m.Crowdfund {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCrowdfundRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCrowdfundRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCrowdfundRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCrowdfundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCrowdfundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCrowdfundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crowdfund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Crowdfund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCrowdfundRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCrowdfundRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCrowdfundRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCrowdfundResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCrowdfundResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCrowdfundResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crowdfund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Crowdfund = append(m.Crowdfund, Crowdfund{})
			if err := m.Crowdfund[len(m.Crowdfund)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
