// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crowdfund/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgLaunchCampaing struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Total    string `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	Amount   string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Deadline string `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Fee      string `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	Owner    string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	State    string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *MsgLaunchCampaing) Reset()         { *m = MsgLaunchCampaing{} }
func (m *MsgLaunchCampaing) String() string { return proto.CompactTextString(m) }
func (*MsgLaunchCampaing) ProtoMessage()    {}
func (*MsgLaunchCampaing) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{0}
}
func (m *MsgLaunchCampaing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLaunchCampaing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLaunchCampaing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLaunchCampaing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLaunchCampaing.Merge(m, src)
}
func (m *MsgLaunchCampaing) XXX_Size() int {
	return m.Size()
}
func (m *MsgLaunchCampaing) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLaunchCampaing.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLaunchCampaing proto.InternalMessageInfo

func (m *MsgLaunchCampaing) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLaunchCampaing) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *MsgLaunchCampaing) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *MsgLaunchCampaing) GetDeadline() string {
	if m != nil {
		return m.Deadline
	}
	return ""
}

func (m *MsgLaunchCampaing) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *MsgLaunchCampaing) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgLaunchCampaing) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type MsgLaunchCampaingResponse struct {
}

func (m *MsgLaunchCampaingResponse) Reset()         { *m = MsgLaunchCampaingResponse{} }
func (m *MsgLaunchCampaingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLaunchCampaingResponse) ProtoMessage()    {}
func (*MsgLaunchCampaingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{1}
}
func (m *MsgLaunchCampaingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLaunchCampaingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLaunchCampaingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLaunchCampaingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLaunchCampaingResponse.Merge(m, src)
}
func (m *MsgLaunchCampaingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLaunchCampaingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLaunchCampaingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLaunchCampaingResponse proto.InternalMessageInfo

type MsgPledgeToken struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Amount  string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgPledgeToken) Reset()         { *m = MsgPledgeToken{} }
func (m *MsgPledgeToken) String() string { return proto.CompactTextString(m) }
func (*MsgPledgeToken) ProtoMessage()    {}
func (*MsgPledgeToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{2}
}
func (m *MsgPledgeToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPledgeToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPledgeToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPledgeToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPledgeToken.Merge(m, src)
}
func (m *MsgPledgeToken) XXX_Size() int {
	return m.Size()
}
func (m *MsgPledgeToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPledgeToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPledgeToken proto.InternalMessageInfo

func (m *MsgPledgeToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgPledgeToken) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgPledgeToken) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MsgPledgeTokenResponse struct {
}

func (m *MsgPledgeTokenResponse) Reset()         { *m = MsgPledgeTokenResponse{} }
func (m *MsgPledgeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPledgeTokenResponse) ProtoMessage()    {}
func (*MsgPledgeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{3}
}
func (m *MsgPledgeTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPledgeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPledgeTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPledgeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPledgeTokenResponse.Merge(m, src)
}
func (m *MsgPledgeTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPledgeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPledgeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPledgeTokenResponse proto.InternalMessageInfo

type MsgClaimToken struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgClaimToken) Reset()         { *m = MsgClaimToken{} }
func (m *MsgClaimToken) String() string { return proto.CompactTextString(m) }
func (*MsgClaimToken) ProtoMessage()    {}
func (*MsgClaimToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{4}
}
func (m *MsgClaimToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimToken.Merge(m, src)
}
func (m *MsgClaimToken) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimToken proto.InternalMessageInfo

func (m *MsgClaimToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgClaimToken) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgClaimTokenResponse struct {
}

func (m *MsgClaimTokenResponse) Reset()         { *m = MsgClaimTokenResponse{} }
func (m *MsgClaimTokenResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimTokenResponse) ProtoMessage()    {}
func (*MsgClaimTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{5}
}
func (m *MsgClaimTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimTokenResponse.Merge(m, src)
}
func (m *MsgClaimTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimTokenResponse proto.InternalMessageInfo

type MsgWithdrawPledge struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgWithdrawPledge) Reset()         { *m = MsgWithdrawPledge{} }
func (m *MsgWithdrawPledge) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawPledge) ProtoMessage()    {}
func (*MsgWithdrawPledge) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{6}
}
func (m *MsgWithdrawPledge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawPledge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawPledge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawPledge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawPledge.Merge(m, src)
}
func (m *MsgWithdrawPledge) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawPledge) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawPledge.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawPledge proto.InternalMessageInfo

func (m *MsgWithdrawPledge) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgWithdrawPledge) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgWithdrawPledgeResponse struct {
}

func (m *MsgWithdrawPledgeResponse) Reset()         { *m = MsgWithdrawPledgeResponse{} }
func (m *MsgWithdrawPledgeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgWithdrawPledgeResponse) ProtoMessage()    {}
func (*MsgWithdrawPledgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{7}
}
func (m *MsgWithdrawPledgeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWithdrawPledgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWithdrawPledgeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWithdrawPledgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWithdrawPledgeResponse.Merge(m, src)
}
func (m *MsgWithdrawPledgeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgWithdrawPledgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWithdrawPledgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWithdrawPledgeResponse proto.InternalMessageInfo

type MsgCancelCampaign struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCancelCampaign) Reset()         { *m = MsgCancelCampaign{} }
func (m *MsgCancelCampaign) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCampaign) ProtoMessage()    {}
func (*MsgCancelCampaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{8}
}
func (m *MsgCancelCampaign) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCampaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCampaign.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCampaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCampaign.Merge(m, src)
}
func (m *MsgCancelCampaign) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCampaign) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCampaign.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCampaign proto.InternalMessageInfo

func (m *MsgCancelCampaign) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCancelCampaign) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgCancelCampaignResponse struct {
}

func (m *MsgCancelCampaignResponse) Reset()         { *m = MsgCancelCampaignResponse{} }
func (m *MsgCancelCampaignResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCampaignResponse) ProtoMessage()    {}
func (*MsgCancelCampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa4dd01fc39511c4, []int{9}
}
func (m *MsgCancelCampaignResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCampaignResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCampaignResponse.Merge(m, src)
}
func (m *MsgCancelCampaignResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCampaignResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgLaunchCampaing)(nil), "cosmonaut.crowdfund.crowdfund.MsgLaunchCampaing")
	proto.RegisterType((*MsgLaunchCampaingResponse)(nil), "cosmonaut.crowdfund.crowdfund.MsgLaunchCampaingResponse")
	proto.RegisterType((*MsgPledgeToken)(nil), "cosmonaut.crowdfund.crowdfund.MsgPledgeToken")
	proto.RegisterType((*MsgPledgeTokenResponse)(nil), "cosmonaut.crowdfund.crowdfund.MsgPledgeTokenResponse")
	proto.RegisterType((*MsgClaimToken)(nil), "cosmonaut.crowdfund.crowdfund.MsgClaimToken")
	proto.RegisterType((*MsgClaimTokenResponse)(nil), "cosmonaut.crowdfund.crowdfund.MsgClaimTokenResponse")
	proto.RegisterType((*MsgWithdrawPledge)(nil), "cosmonaut.crowdfund.crowdfund.MsgWithdrawPledge")
	proto.RegisterType((*MsgWithdrawPledgeResponse)(nil), "cosmonaut.crowdfund.crowdfund.MsgWithdrawPledgeResponse")
	proto.RegisterType((*MsgCancelCampaign)(nil), "cosmonaut.crowdfund.crowdfund.MsgCancelCampaign")
	proto.RegisterType((*MsgCancelCampaignResponse)(nil), "cosmonaut.crowdfund.crowdfund.MsgCancelCampaignResponse")
}

func init() { proto.RegisterFile("crowdfund/tx.proto", fileDescriptor_aa4dd01fc39511c4) }

var fileDescriptor_aa4dd01fc39511c4 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8b, 0xd4, 0x30,
	0x18, 0x9e, 0xce, 0xcc, 0xce, 0xea, 0x2b, 0x16, 0x0d, 0xba, 0xc6, 0x8a, 0x45, 0x7a, 0xf2, 0xa0,
	0x9d, 0xc5, 0x0f, 0xd0, 0x83, 0x17, 0xe7, 0x26, 0x16, 0xa4, 0x08, 0x82, 0xb7, 0x6c, 0x93, 0xcd,
	0x14, 0xdb, 0xa4, 0x34, 0x29, 0xb3, 0xc2, 0xfe, 0x08, 0xff, 0x8c, 0xff, 0xc1, 0xe3, 0x1e, 0x3d,
	0xca, 0x0c, 0xf8, 0x3b, 0xa4, 0xa9, 0xd3, 0x69, 0xbb, 0x5f, 0xed, 0x2d, 0xcf, 0x9b, 0xf7, 0x79,
	0x9e, 0xe4, 0xcd, 0x43, 0x00, 0x45, 0xb9, 0x5c, 0xd1, 0xe3, 0x42, 0xd0, 0xb9, 0x3e, 0xf1, 0xb3,
	0x5c, 0x6a, 0x89, 0x1e, 0x47, 0x52, 0xa5, 0x52, 0x90, 0x42, 0xfb, 0xf5, 0xee, 0x6e, 0xe5, 0xfd,
	0xb4, 0xe0, 0x6e, 0xa0, 0xf8, 0x47, 0x52, 0x88, 0x68, 0xb9, 0x20, 0x69, 0x46, 0x62, 0xc1, 0x11,
	0x86, 0xfd, 0x28, 0x67, 0x44, 0xcb, 0x1c, 0x5b, 0x4f, 0xac, 0xa7, 0x37, 0xc3, 0x2d, 0x44, 0xf7,
	0x60, 0x4f, 0x4b, 0x4d, 0x12, 0x3c, 0x36, 0xf5, 0x0a, 0xa0, 0x03, 0x98, 0x91, 0x54, 0x16, 0x42,
	0xe3, 0x89, 0x29, 0xff, 0x47, 0xc8, 0x81, 0x1b, 0x94, 0x11, 0x9a, 0xc4, 0x82, 0xe1, 0xa9, 0xd9,
	0xa9, 0x31, 0xba, 0x03, 0x93, 0x63, 0xc6, 0xf0, 0x9e, 0x29, 0x97, 0xcb, 0x52, 0x5b, 0xae, 0x04,
	0xcb, 0xf1, 0xac, 0xd2, 0x36, 0xa0, 0xac, 0x2a, 0x4d, 0x34, 0xc3, 0xfb, 0x55, 0xd5, 0x00, 0xef,
	0x11, 0x3c, 0x3c, 0x77, 0xec, 0x90, 0xa9, 0x4c, 0x0a, 0xc5, 0xbc, 0x10, 0xec, 0x40, 0xf1, 0x4f,
	0x09, 0xa3, 0x9c, 0x7d, 0x96, 0xdf, 0x98, 0xb8, 0xe2, 0x42, 0x36, 0x8c, 0x63, 0x6a, 0x6e, 0x33,
	0x0d, 0xc7, 0x31, 0xbd, 0xec, 0x2a, 0x1e, 0x86, 0x83, 0xb6, 0x66, 0xed, 0xf6, 0x16, 0x6e, 0x07,
	0x8a, 0x2f, 0x12, 0x12, 0xa7, 0x03, 0xcd, 0xbc, 0x07, 0x70, 0xbf, 0x45, 0xad, 0x35, 0xdf, 0x99,
	0x57, 0xf9, 0x12, 0xeb, 0x25, 0xcd, 0xc9, 0xaa, 0x72, 0x1d, 0xa0, 0x5b, 0x4d, 0xa7, 0x4d, 0xef,
	0x68, 0x2f, 0x88, 0x88, 0x58, 0x52, 0x8d, 0x8e, 0x8b, 0xc1, 0xda, 0x6d, 0xfa, 0x56, 0xfb, 0xc5,
	0xdf, 0x29, 0x4c, 0x02, 0xc5, 0xd1, 0x29, 0xd8, 0x9d, 0x48, 0x1d, 0xfa, 0x57, 0x06, 0xd1, 0x3f,
	0xf7, 0x9a, 0xce, 0x9b, 0xa1, 0x8c, 0xed, 0x29, 0x90, 0x82, 0x5b, 0xcd, 0xc7, 0x7f, 0x7e, 0xbd,
	0x50, 0xa3, 0xdd, 0x79, 0x3d, 0xa8, 0xbd, 0x36, 0xcd, 0x00, 0x1a, 0x19, 0x78, 0x76, 0xbd, 0xc8,
	0xae, 0xdb, 0x79, 0x35, 0xa4, 0xbb, 0x76, 0x3c, 0x05, 0xbb, 0x93, 0x90, 0x1e, 0x43, 0x6e, 0x33,
	0xfa, 0x0c, 0xf9, 0xe2, 0x18, 0x95, 0xee, 0x9d, 0x0c, 0xf5, 0x70, 0x6f, 0x33, 0xfa, 0xb8, 0x5f,
	0x1c, 0xb4, 0xf7, 0x1f, 0x7e, 0xad, 0x5d, 0xeb, 0x6c, 0xed, 0x5a, 0x7f, 0xd6, 0xae, 0xf5, 0x63,
	0xe3, 0x8e, 0xce, 0x36, 0xee, 0xe8, 0xf7, 0xc6, 0x1d, 0x7d, 0x3d, 0xe4, 0xb1, 0x5e, 0x16, 0x47,
	0x7e, 0x24, 0xd3, 0x79, 0xad, 0x3e, 0xdf, 0xfd, 0x8c, 0x27, 0x8d, 0xb5, 0xfe, 0x9e, 0x31, 0x75,
	0x34, 0x33, 0x3f, 0xe5, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0xcd, 0xdf, 0x8f, 0x3f,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	LaunchCampaing(ctx context.Context, in *MsgLaunchCampaing, opts ...grpc.CallOption) (*MsgLaunchCampaingResponse, error)
	PledgeToken(ctx context.Context, in *MsgPledgeToken, opts ...grpc.CallOption) (*MsgPledgeTokenResponse, error)
	ClaimToken(ctx context.Context, in *MsgClaimToken, opts ...grpc.CallOption) (*MsgClaimTokenResponse, error)
	WithdrawPledge(ctx context.Context, in *MsgWithdrawPledge, opts ...grpc.CallOption) (*MsgWithdrawPledgeResponse, error)
	CancelCampaign(ctx context.Context, in *MsgCancelCampaign, opts ...grpc.CallOption) (*MsgCancelCampaignResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LaunchCampaing(ctx context.Context, in *MsgLaunchCampaing, opts ...grpc.CallOption) (*MsgLaunchCampaingResponse, error) {
	out := new(MsgLaunchCampaingResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Msg/LaunchCampaing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PledgeToken(ctx context.Context, in *MsgPledgeToken, opts ...grpc.CallOption) (*MsgPledgeTokenResponse, error) {
	out := new(MsgPledgeTokenResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Msg/PledgeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ClaimToken(ctx context.Context, in *MsgClaimToken, opts ...grpc.CallOption) (*MsgClaimTokenResponse, error) {
	out := new(MsgClaimTokenResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Msg/ClaimToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) WithdrawPledge(ctx context.Context, in *MsgWithdrawPledge, opts ...grpc.CallOption) (*MsgWithdrawPledgeResponse, error) {
	out := new(MsgWithdrawPledgeResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Msg/WithdrawPledge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelCampaign(ctx context.Context, in *MsgCancelCampaign, opts ...grpc.CallOption) (*MsgCancelCampaignResponse, error) {
	out := new(MsgCancelCampaignResponse)
	err := c.cc.Invoke(ctx, "/cosmonaut.crowdfund.crowdfund.Msg/CancelCampaign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	LaunchCampaing(context.Context, *MsgLaunchCampaing) (*MsgLaunchCampaingResponse, error)
	PledgeToken(context.Context, *MsgPledgeToken) (*MsgPledgeTokenResponse, error)
	ClaimToken(context.Context, *MsgClaimToken) (*MsgClaimTokenResponse, error)
	WithdrawPledge(context.Context, *MsgWithdrawPledge) (*MsgWithdrawPledgeResponse, error)
	CancelCampaign(context.Context, *MsgCancelCampaign) (*MsgCancelCampaignResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LaunchCampaing(ctx context.Context, req *MsgLaunchCampaing) (*MsgLaunchCampaingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchCampaing not implemented")
}
func (*UnimplementedMsgServer) PledgeToken(ctx context.Context, req *MsgPledgeToken) (*MsgPledgeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PledgeToken not implemented")
}
func (*UnimplementedMsgServer) ClaimToken(ctx context.Context, req *MsgClaimToken) (*MsgClaimTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimToken not implemented")
}
func (*UnimplementedMsgServer) WithdrawPledge(ctx context.Context, req *MsgWithdrawPledge) (*MsgWithdrawPledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawPledge not implemented")
}
func (*UnimplementedMsgServer) CancelCampaign(ctx context.Context, req *MsgCancelCampaign) (*MsgCancelCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCampaign not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LaunchCampaing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLaunchCampaing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LaunchCampaing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Msg/LaunchCampaing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LaunchCampaing(ctx, req.(*MsgLaunchCampaing))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PledgeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPledgeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PledgeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Msg/PledgeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PledgeToken(ctx, req.(*MsgPledgeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ClaimToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Msg/ClaimToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimToken(ctx, req.(*MsgClaimToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_WithdrawPledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgWithdrawPledge)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).WithdrawPledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Msg/WithdrawPledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).WithdrawPledge(ctx, req.(*MsgWithdrawPledge))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelCampaign)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmonaut.crowdfund.crowdfund.Msg/CancelCampaign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelCampaign(ctx, req.(*MsgCancelCampaign))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmonaut.crowdfund.crowdfund.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchCampaing",
			Handler:    _Msg_LaunchCampaing_Handler,
		},
		{
			MethodName: "PledgeToken",
			Handler:    _Msg_PledgeToken_Handler,
		},
		{
			MethodName: "ClaimToken",
			Handler:    _Msg_ClaimToken_Handler,
		},
		{
			MethodName: "WithdrawPledge",
			Handler:    _Msg_WithdrawPledge_Handler,
		},
		{
			MethodName: "CancelCampaign",
			Handler:    _Msg_CancelCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crowdfund/tx.proto",
}

func (m *MsgLaunchCampaing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLaunchCampaing) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLaunchCampaing) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintTx(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Fee) > 0 {
		i -= len(m.Fee)
		copy(dAtA[i:], m.Fee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Fee)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Deadline) > 0 {
		i -= len(m.Deadline)
		copy(dAtA[i:], m.Deadline)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Deadline)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Total) > 0 {
		i -= len(m.Total)
		copy(dAtA[i:], m.Total)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Total)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLaunchCampaingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLaunchCampaingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLaunchCampaingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPledgeToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPledgeToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPledgeToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPledgeTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPledgeTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPledgeTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgClaimToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawPledge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawPledge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawPledge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgWithdrawPledgeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWithdrawPledgeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWithdrawPledgeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelCampaign) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCampaign) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCampaign) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelCampaignResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCampaignResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCampaignResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgLaunchCampaing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Total)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Deadline)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Fee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgLaunchCampaingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPledgeToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPledgeTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgClaimToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgClaimTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgWithdrawPledge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgWithdrawPledgeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelCampaign) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgCancelCampaignResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgLaunchCampaing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLaunchCampaing: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLaunchCampaing: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Total = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deadline", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deadline = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLaunchCampaingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLaunchCampaingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLaunchCampaingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPledgeToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPledgeToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPledgeToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPledgeTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPledgeTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPledgeTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawPledge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawPledge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawPledge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgWithdrawPledgeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWithdrawPledgeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWithdrawPledgeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCampaign) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCampaign: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCampaign: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCampaignResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCampaignResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCampaignResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
